# PHP CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
#
version: 2.0
workflows:
  verify_standards:
    jobs:
      - standard

working_directory: ~/repo

jobs:
  standard:
    docker:
      - image: circleci/php:7.1
    steps:
      - checkout
      - run: composer i
      - run: ./vendor/bin/phpcs .